### ISSUE TITLE
Feat : Sort select filter

### ISSUE THREAD

**Issue by Grezor** [iedr/goodfirstissues#38]
It's been several times, I come to the site. I used it several times, each time I go on the selects, I get lost.

I suggest sorting, or alphabetizing.  This will allow other users to better select the desired languages. Instead of typing directly the language. I would like to have feedback to discuss this 

@iedr 

![image](https://user-images.githubusercontent.com/38507456/147872995-de9e2b13-40de-4004-8be0-06a33201fe49.png)

**Comment by iedr** [comment]
Hi, @Grezor thanks for pointing this out. The list is sorted based on the number of issues that involve that programming language. For example, in your screenshot, there are 407 issues tagged under JavaScript.

Do you think sorting alphabetically will be more helpful/intuitive?

**Comment by Grezor** [comment]
I think just putting the name in alphabetical order would make it easier to find. But as far as the screenshot is concerned, I don't pay attention to the numbers. After that, I would need other opinions.

Another suggestion is to put : 
```md
Javascript (407) => Javascript (407 issues) or Javascript

and in the page where there are the issues, display the number of issues
```

**Comment by iedr** [comment]
I think sorting alphabetically and putting `... (X issues)` seems to be fine.

Would you like to do a PR for this?

**Comment by lucalves** [comment]
Hello everyone! I opened the #39 that adds the word _Issues_ after the counter.
