### ISSUE TITLE
filter on contributor's spoken language

### ISSUE THREAD

**Issue by MataMercer** [iedr/goodfirstissues#40]
i don't know if its possible, but I'd like to filter based on language of the contributor. I can't really read anything by chinese or russian authors.

**Comment by Kirito-Excalibur** [comment]
You mean you want it to have documentation in other languages?

**Comment by MataMercer** [comment]
no. theres a lot of good first issues that aren't in English. I only want to see ones that are in English.

**Comment by iedr** [comment]
Hi @MataMercer and @Kirito-Excalibur 
The issues are searched using Github's API which I don't think offers an option to search by (human) language, only programming language.
