### ISSUE TITLE
A detail contributing guide

### ISSUE THREAD

**Issue by Sajiyah-Salat** [iedr/goodfirstissues#43]
The only thing about this website that I like is the.com ending; otherwise, the user interface needs to be updated, and there isn't a comprehensive tutorial for contributing, which is a problem because I want to include my [project](https://github.com/Sajiyah-Salat/BlogWeb) here. I was given no instructions for doing the same. I will try to work on this issue. Can you please assign me that?

**Comment by iedr** [comment]
Hi @Sajiyah-Salat, the website does not work by including projects. It works by searching for issues/projects tagged with "Good First Issue" on Github using its API. There isn't a list of projects that are included by default.
