### ISSUE TITLE
long loading time with error.

### ISSUE THREAD

**Issue by ritesh-karankal** [iedr/goodfirstissues#44]
I've been using goodfirstissues to find issues to fix, but over the past few days, I've had trouble getting the website to load on my desktop computer in any of the browsers. The mobile website is working properly.
I've tried clearing the cache and cookies, but the issue persists.
After a loading period, it displays "Oops! Seems like there is no issue to show! Refresh to try again."

If it's an issue specific to my device or browser settings and a problem that just I have.
Please offer some solutions to the problem. 

![image](https://user-images.githubusercontent.com/71586008/208369287-52706a28-1bc3-4476-b802-1bf80bf5ec80.png)
![image](https://user-images.githubusercontent.com/71586008/208369543-d42d67bc-c88e-4620-b029-a9d6f1da68ba.png)

![image](https://user-images.githubusercontent.com/71586008/208369841-d1142131-d869-4044-9bdb-13bbd3f6c851.png)

**Comment by Aditya753b** [comment]
same for me too,thought its just my browser...

**Comment by iedr** [comment]
Hi @ritesh-karankal and @Aditya753b, the website is hosted on GitHub Pages, and reads the data from [here](https://github.com/iedr/goodfirstissues/blob/master/backend/data.json). If the loading is slow, it might be because GitHub Pages is slow, or reading from the data is slow. As of now, the website works fine for me. Do let me know if you face further issues!

**Comment by Kaushik-Iyer** [comment]
The site is not working for me as well

**Comment by rkmdCodes** [comment]
site is not working for me  i am also having same issue

**Comment by Sivayogeith** [comment]
@ritesh-karankal Are you using Jio?
I'm using Jio and got the same loading problem and i figured out that this website uses raw.githubusercontent.com as their database. And I think Jio banned raw.githubusercontent.com

You can get more info about it [here](https://github.com/orgs/community/discussions/42655#discussioncomment-4870126).

**Comment by Aditya753b** [comment]
> @ritesh-karankal Are you using Jio? I'm using Jio and got the same loading problem and i figured out that this website uses raw.githubusercontent.com as their database. And unfortunately I think [Jio blocked raw.githubusercontent.com](https://github.com/orgs/community/discussions/42655#discussioncomment-4555366)
> 
> You can get more info about it [here](https://github.com/orgs/community/discussions/42655).

yeah i think thats the issue

**Comment by ritesh-karankal** [comment]
> @ritesh-karankal Are you using Jio? I'm using Jio and got the same loading problem and i figured out that this website uses raw.githubusercontent.com as their database. And unfortunately I think [Jio blocked raw.githubusercontent.com](https://github.com/orgs/community/discussions/42655#discussioncomment-4555366)
> 
> You can get more info about it [here](https://github.com/orgs/community/discussions/42655).

Yes, that is the case. Thanks for sharing the resource!

**Comment by Sivayogeith** [comment]
> > @ritesh-karankal Are you using Jio? I'm using Jio and got the same loading problem and i figured out that this website uses raw.githubusercontent.com as their database. And unfortunately I think [Jio blocked raw.githubusercontent.com](https://github.com/orgs/community/discussions/42655#discussioncomment-4555366)
> > You can get more info about it [here](https://github.com/orgs/community/discussions/42655).
> 
> Yes, that is the case. Thanks for sharing the resource!

BTW, now I switched to Asiannet broadband and it works!
