### ISSUE TITLE
Issues are not working properly

### ISSUE THREAD

**Issue by AlimurtuzaCodes** [iedr/goodfirstissues#48]
### Latest Issues are not showing it is showing old ones.

Issues are not updated.

### Now

![image](https://github.com/iedr/goodfirstissues/assets/88965204/71ef92aa-b53b-482c-9a4a-e0736f0ed49a)

**Comment by harsiddhdave44** [comment]
@AlimurtuzaCodes The workflow is failing due to which the data is not being updated. I've raised a PR for the fix, which should do the work.
