### ISSUE TITLE
How to add GFIs of the new project

### ISSUE THREAD

**Issue by rkazants** [iedr/goodfirstissues#58]
Hi @iedr,

Is it possible to have good first issues of [OpenVINO project](https://github.com/openvinotoolkit/openvino) to be listed on your site?
Please advice how to do this if possible.

Best regards,
Roman

**Comment by iedr** [comment]
Hi @rkazants 
Please refer to this issue here - https://github.com/iedr/goodfirstissues/issues/24#issuecomment-730960415

**Comment by rkazants** [comment]
Hi @iedr,

Thanks for the response. We have GFIs in our project: https://github.com/openvinotoolkit/openvino/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22. So we seem to be on a right way:)

Best regards,
Roman

**Comment by rkazants** [comment]
@iedr, one more question is how often do you perform searching for new repos/GFIs?

Best regards,
Roman

**Comment by iedr** [comment]
@rkazants Currently, 3 times a day. You can see this here - https://github.com/iedr/goodfirstissues/blob/master/.github/workflows/go-write-to-file.yml#L6

**Comment by rkazants** [comment]
@iedr, a bit strange that I can't see our project listed in your website: https://goodfirstissues.com/. Though, we have created GFIs two month (or more) ago and permanently update it. Can you please check?

Best regards,
Roman

**Comment by iedr** [comment]
@iedr We list the most recent issues, sorted by creation date. 
If the issue was created months ago, it will probably not be seen here.

**Comment by rkazants** [comment]
Hi @iedr, we have active GFIs created one week ago, two weeks ago, three weeks ago (https://github.com/openvinotoolkit/openvino/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). And they are not listed.

Best regards,
Roman

**Comment by iedr** [comment]
@rkazants If you navigate to the last page, you can see that the oldest issue listed is 5 days ago. So all the issues displayed on the website are at most 5 days old.

**Comment by rkazants** [comment]
@iedr, I got it. Thanks for the explanaition.

Best regards,
Roman
