### ISSUE TITLE
I want to add my project, How can I do so ??

### ISSUE THREAD

**Issue by Akshat111111** [iedr/goodfirstissues#59]

**Comment by itfibonacci** [comment]
same. there should be a feature/documentation on how to add our projects to here.

for example: https://goodfirstissue.dev - has a button for this which takes to the Readme and explains how to add a project/ what the requirements are.

**Comment by iedr** [comment]
Hi @Akshat111111 and @itfibonacci 
Please refer to the PR comment here - https://github.com/iedr/goodfirstissues/issues/24#issuecomment-730960415

**Comment by Akshat111111** [comment]
sure Thankyou so much for your response

**Comment by itfibonacci** [comment]
@iedr  thanks, while I appreciate your work but that is a very arbitrary process.
